export const movies = [
  {
    adult: false,
    backdrop_path: "/qTkJ6kbTeSjqfHCFCmWnfWZJOtm.jpg",
    genre_ids: [10751, 16, 12, 35, 14],
    id: 438148,
    original_language: "en",
    original_title: "Minions: The Rise of Gru",
    overview:
      "A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.",
    popularity: 11293.05,
    poster_path: "/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg",
    release_date: "2022-06-29",
    title: "Minions: The Rise of Gru",
    video: false,
    vote_average: 7.8,
    vote_count: 210,
  },
  {
    adult: false,
    backdrop_path: "/wcKFYIiVDvRURrzglV9kGu7fpfY.jpg",
    genre_ids: [14, 28, 12],
    id: 453395,
    original_language: "en",
    original_title: "Doctor Strange in the Multiverse of Madness",
    overview:
      "Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.",
    popularity: 7349.714,
    poster_path: "/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg",
    release_date: "2022-05-04",
    title: "Doctor Strange in the Multiverse of Madness",
    video: false,
    vote_average: 7.5,
    vote_count: 4217,
  },
  {
    adult: false,
    backdrop_path: "/p1F51Lvj3sMopG948F5HsBbl43C.jpg",
    genre_ids: [28, 12, 14],
    id: 616037,
    original_language: "en",
    original_title: "Thor: Love and Thunder",
    overview:
      "After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now inexplicably wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.",
    popularity: 5473.405,
    poster_path: "/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
    release_date: "2022-07-06",
    title: "Thor: Love and Thunder",
    video: false,
    vote_average: 7.1,
    vote_count: 503,
  },
  {
    adult: false,
    backdrop_path: "/wo3l9p0S7pcvwlzlndtKgq0peRJ.jpg",
    genre_ids: [12, 28, 878],
    id: 507086,
    original_language: "en",
    original_title: "Jurassic World Dominion",
    overview:
      "Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history’s most fearsome creatures.",
    popularity: 3328.407,
    poster_path: "/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg",
    release_date: "2022-06-01",
    title: "Jurassic World Dominion",
    video: false,
    vote_average: 6.6,
    vote_count: 1054,
  },
  {
    adult: false,
    backdrop_path: "/ta17TltHGdZ5PZz6oUD3N5BRurb.jpg",
    genre_ids: [53],
    id: 924482,
    original_language: "en",
    original_title: "The Ledge",
    overview:
      "A rock climbing adventure between two friends turns into a terrifying nightmare. After Kelly captures the murder of her best friend on camera, she becomes the next target of a tight-knit group of friends who will stop at nothing to destroy the evidence and anyone in their way. Desperate for her safety, she begins a treacherous climb up a mountain cliff and her survival instincts are put to the test when she becomes trapped with the killers just 20 feet away.",
    popularity: 3264.421,
    poster_path: "/dHKfsdNcEPw7YIWFPIhqiuWrSAb.jpg",
    release_date: "2022-02-18",
    title: "The Ledge",
    video: false,
    vote_average: 6.5,
    vote_count: 40,
  },
  {
    adult: false,
    backdrop_path: "/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg",
    genre_ids: [28, 12, 10751, 35],
    id: 675353,
    original_language: "en",
    original_title: "Sonic the Hedgehog 2",
    overview:
      "After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.",
    popularity: 2543.199,
    poster_path: "/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg",
    release_date: "2022-03-30",
    title: "Sonic the Hedgehog 2",
    video: false,
    vote_average: 7.7,
    vote_count: 2427,
  },
  {
    adult: false,
    backdrop_path: "/zGLHX92Gk96O1DJvLil7ObJTbaL.jpg",
    genre_ids: [14, 12, 28],
    id: 338953,
    original_language: "en",
    original_title: "Fantastic Beasts: The Secrets of Dumbledore",
    overview:
      "Professor Albus Dumbledore knows the powerful, dark wizard Gellert Grindelwald is moving to seize control of the wizarding world. Unable to stop him alone, he entrusts magizoologist Newt Scamander to lead an intrepid team of wizards and witches. They soon encounter an array of old and new beasts as they clash with Grindelwald's growing legion of followers.",
    popularity: 2532.118,
    poster_path: "/jrgifaYeUtTnaH7NF5Drkgjg2MB.jpg",
    release_date: "2022-04-06",
    title: "Fantastic Beasts: The Secrets of Dumbledore",
    video: false,
    vote_average: 6.8,
    vote_count: 2198,
  },
  {
    adult: false,
    backdrop_path: "/t0mwKhUDa62hdhdKSsN4xMfhY5Z.jpg",
    genre_ids: [18, 35],
    id: 626735,
    original_language: "en",
    original_title: "Dog",
    overview:
      "An army ranger and his dog embark on a road trip along the Pacific Coast Highway to attend a friend's funeral.",
    popularity: 2514.522,
    poster_path: "/rkpLvPDe0ZE62buUS32exdNr7zD.jpg",
    release_date: "2022-02-17",
    title: "Dog",
    video: false,
    vote_average: 7.4,
    vote_count: 578,
  },
  {
    adult: false,
    backdrop_path: "/ocUp7DJBIc8VJgLEw1prcyK1dYv.jpg",
    genre_ids: [28, 12, 878],
    id: 634649,
    original_language: "en",
    original_title: "Spider-Man: No Way Home",
    overview:
      "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    popularity: 2172.096,
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    release_date: "2021-12-15",
    title: "Spider-Man: No Way Home",
    video: false,
    vote_average: 8.1,
    vote_count: 14026,
  },
  {
    adult: false,
    backdrop_path: "/1Ds7xy7ILo8u2WWxdnkJth1jQVT.jpg",
    genre_ids: [28, 12, 35],
    id: 752623,
    original_language: "en",
    original_title: "The Lost City",
    overview:
      "A reclusive romance novelist was sure nothing could be worse than getting stuck on a book tour with her cover model until a kidnapping attempt sweeps them both into a cutthroat jungle adventure, proving life can be so much stranger, and more romantic, than any of her paperback fictions.",
    popularity: 2168.979,
    poster_path: "/neMZH82Stu91d3iqvLdNQfqPPyl.jpg",
    release_date: "2022-03-24",
    title: "The Lost City",
    video: false,
    vote_average: 6.8,
    vote_count: 1456,
  },
  {
    adult: false,
    backdrop_path: "/gG9fTyDL03fiKnOpf2tr01sncnt.jpg",
    genre_ids: [28, 878, 14],
    id: 526896,
    original_language: "en",
    original_title: "Morbius",
    overview:
      "Dangerously ill with a rare blood disorder, and determined to save others suffering his same fate, Dr. Michael Morbius attempts a desperate gamble. What at first appears to be a radical success soon reveals itself to be a remedy potentially worse than the disease.",
    popularity: 2075.718,
    poster_path: "/6JjfSchsU6daXk2AKX8EEBjO3Fm.jpg",
    release_date: "2022-03-30",
    title: "Morbius",
    video: false,
    vote_average: 6.4,
    vote_count: 2003,
  },
  {
    adult: false,
    backdrop_path: "/3oTeRLZQ16HGmVXAvEnVh90PhS6.jpg",
    genre_ids: [28, 35, 53],
    id: 667739,
    original_language: "en",
    original_title: "The Man From Toronto",
    overview:
      "In a case of mistaken identity, the world’s deadliest assassin, known as the Man from Toronto, and a New York City screw-up are forced to team up after being confused for each other at an Airbnb.",
    popularity: 1868.322,
    poster_path: "/uTCfTibqtk4f90cC59bLPMOmsfc.jpg",
    release_date: "2022-06-24",
    title: "The Man From Toronto",
    video: false,
    vote_average: 6.2,
    vote_count: 296,
  },
  {
    adult: false,
    backdrop_path: "/v7hdWmLh6VLgZQgkbHDxAa17M47.jpg",
    genre_ids: [28, 80, 53],
    id: 852592,
    original_language: "es",
    original_title: "Centauro",
    overview:
      "Rafa's hooked on the pure, fiery feelings he gets from speed racing, but when his kid's mom gets mixed up with drug dealers, he burns rubber to save her.",
    popularity: 1744.72,
    poster_path: "/wOx97MJOxEoR38aoya3lopyrlYC.jpg",
    release_date: "2022-06-15",
    title: "Centauro",
    video: false,
    vote_average: 6.6,
    vote_count: 60,
  },
  {
    adult: false,
    backdrop_path: "/vjnLXptqdxnpNJer5fWgj2OIGhL.jpg",
    genre_ids: [28, 53, 80],
    id: 818397,
    original_language: "en",
    original_title: "Memory",
    overview:
      "Alex, an assassin-for-hire, finds that he's become a target after he refuses to complete a job for a dangerous criminal organization. With the crime syndicate and FBI in hot pursuit, Alex has the skills to stay ahead, except for one thing: he is struggling with severe memory loss, affecting his every move. Alex must question his every action and whom he can ultimately trust.",
    popularity: 1822.672,
    poster_path: "/4Q1n3TwieoULnuaztu9aFjqHDTI.jpg",
    release_date: "2022-04-28",
    title: "Memory",
    video: false,
    vote_average: 7.3,
    vote_count: 483,
  },
  {
    adult: false,
    backdrop_path: "/o31kGDH9GbAZjVLwPYno8XvQGV2.jpg",
    genre_ids: [28, 53],
    id: 777831,
    original_language: "en",
    original_title: "9 Bullets",
    overview:
      "A former burlesque dancer turned author discovers a second chance at life and redemption when she risks everything to rescue her young neighbor after he witnesses his parents’ murder. Now on the run from the local crime boss, who happens to be her longtime ex, she makes a desperate attempt to get the boy to safety.",
    popularity: 1462.35,
    poster_path: "/cuFPxoFopAjFUz4oIMUzpzeTA8I.jpg",
    release_date: "2022-04-14",
    title: "9 Bullets",
    video: false,
    vote_average: 6.1,
    vote_count: 32,
  },
  {
    adult: false,
    backdrop_path: "/jVGHRpSgtE2MQLJhC5q4lXmPNQW.jpg",
    genre_ids: [27, 53, 28],
    id: 960258,
    original_language: "en",
    original_title: "Shark Bait",
    overview:
      "A group of friends enjoying a weekend steal a couple of jetskis racing them out to sea, ending up in a horrific head-on collision. They struggle to find a way home with a badly injured friend while from the waters below predators lurk.",
    popularity: 1631.933,
    poster_path: "/mVVU9zC8snNHlcqYONY2HOsh9ob.jpg",
    release_date: "2022-05-13",
    title: "Shark Bait",
    video: false,
    vote_average: 6.9,
    vote_count: 69,
  },
  {
    adult: false,
    backdrop_path: "/uzZAef6uVqvhY4nLWqVvaq3DQeJ.jpg",
    genre_ids: [53, 80, 18],
    id: 975714,
    original_language: "en",
    original_title: "Collision",
    overview:
      "Over the course of one fateful day, a corrupt businessman and his socialite wife race to save their daughter from a notorious crime lord.",
    popularity: 1738.237,
    poster_path: "/4zsihgkxMZ7MrflNCjkD3ySFJtc.jpg",
    release_date: "2022-06-16",
    title: "Collision",
    video: false,
    vote_average: 6,
    vote_count: 70,
  },
  {
    adult: false,
    backdrop_path: "/aEGiJJP91HsKVTEPy1HhmN0wRLm.jpg",
    genre_ids: [28, 12],
    id: 335787,
    original_language: "en",
    original_title: "Uncharted",
    overview:
      "A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.",
    popularity: 1375.662,
    poster_path: "/rJHC1RUORuUhtfNb4Npclx0xnOf.jpg",
    release_date: "2022-02-10",
    title: "Uncharted",
    video: false,
    vote_average: 7.2,
    vote_count: 2678,
  },
  {
    adult: false,
    backdrop_path: "/fqw8nJLPRgKRyFSDC0xBsC06NGC.jpg",
    genre_ids: [28, 12, 14],
    id: 639933,
    original_language: "en",
    original_title: "The Northman",
    overview:
      "Prince Amleth is on the verge of becoming a man when his father is brutally murdered by his uncle, who kidnaps the boy's mother. Two decades later, Amleth is now a Viking who's on a mission to save his mother, kill his uncle and avenge his father.",
    popularity: 1613.549,
    poster_path: "/8p9zXB7M78nZpm215zHfqpknMeM.jpg",
    release_date: "2022-04-07",
    title: "The Northman",
    video: false,
    vote_average: 7.2,
    vote_count: 1802,
  },
  {
    adult: false,
    backdrop_path: "/ulkWS7Atv0vv33KVCSAmNizAmJd.jpg",
    genre_ids: [878, 53],
    id: 615469,
    original_language: "en",
    original_title: "Spiderhead",
    overview:
      "A prisoner in a state-of-the-art penitentiary begins to question the purpose of the emotion-controlling drugs he's testing for a pharmaceutical genius.",
    popularity: 1673.158,
    poster_path: "/7COPO5B9AOKIB4sEkvNu0wfve3c.jpg",
    release_date: "2022-06-15",
    title: "Spiderhead",
    video: false,
    vote_average: 5.8,
    vote_count: 589,
  },
];
const trending = [
  {
    adult: false,
    backdrop_path: "/p1F51Lvj3sMopG948F5HsBbl43C.jpg",
    genre_ids: [28, 12, 14],
    id: 616037,
    media_type: "movie",
    title: "Thor: Love and Thunder",
    original_language: "en",
    original_title: "Thor: Love and Thunder",
    overview:
      "After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now inexplicably wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.",
    popularity: 5473.405,
    poster_path: "/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
    release_date: "2022-07-06",
    video: false,
    vote_average: 7.084,
    vote_count: 508,
  },
  {
    adult: false,
    backdrop_path: "/wUwizGzbTk5CTiKBnE4Pq1MONwD.jpg",
    genre_ids: [16, 12, 10751, 14],
    id: 560057,
    media_type: "movie",
    title: "The Sea Beast",
    original_language: "en",
    original_title: "The Sea Beast",
    overview:
      "The life of a legendary sea monster hunter is turned upside down when a young girl stows away on his ship.",
    popularity: 96.995,
    poster_path: "/9Zfv4Ap1e8eKOYnZPtYaWhLkk0d.jpg",
    release_date: "2022-06-24",
    video: false,
    vote_average: 7.42,
    vote_count: 87,
  },
  {
    adult: false,
    backdrop_path: "/flTnaBaW1UnQtzGEIoHR7C3OYfy.jpg",
    genre_ids: [12, 28, 878],
    id: 507086,
    media_type: "movie",
    title: "Jurassic World Dominion",
    original_language: "en",
    original_title: "Jurassic World Dominion",
    overview:
      "Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history’s most fearsome creatures.",
    popularity: 3328.407,
    poster_path: "/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg",
    release_date: "2022-06-01",
    video: false,
    vote_average: 6.58,
    vote_count: 1057,
  },
  {
    adult: false,
    backdrop_path: "/wcKFYIiVDvRURrzglV9kGu7fpfY.jpg",
    genre_ids: [14, 28, 12],
    id: 453395,
    media_type: "movie",
    title: "Doctor Strange in the Multiverse of Madness",
    original_language: "en",
    original_title: "Doctor Strange in the Multiverse of Madness",
    overview:
      "Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.",
    popularity: 7349.714,
    poster_path: "/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg",
    release_date: "2022-05-04",
    video: false,
    vote_average: 7.53,
    vote_count: 4219,
  },
  {
    adult: false,
    backdrop_path: "/mGVrXeIjyecj6TKmwPVpHlscEmw.jpg",
    genre_ids: [10765, 10759],
    id: 76479,
    media_type: "tv",
    name: "The Boys",
    origin_country: ["US"],
    original_language: "en",
    original_name: "The Boys",
    overview:
      "A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.",
    popularity: 3953.369,
    poster_path: "/stTEycfG9928HYGEISBFaG1ngjM.jpg",
    first_air_date: "2019-07-25",
    vote_average: 8.454,
    vote_count: 6590,
  },
  {
    adult: false,
    backdrop_path: "/qTkJ6kbTeSjqfHCFCmWnfWZJOtm.jpg",
    genre_ids: [10751, 16, 12, 35, 14],
    id: 438148,
    media_type: "movie",
    title: "Minions: The Rise of Gru",
    original_language: "en",
    original_title: "Minions: The Rise of Gru",
    overview:
      "A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.",
    popularity: 11293.05,
    poster_path: "/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg",
    release_date: "2022-06-29",
    video: false,
    vote_average: 7.765,
    vote_count: 211,
  },
  {
    adult: false,
    backdrop_path: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    genre_ids: [18, 10765, 9648],
    id: 66732,
    media_type: "tv",
    name: "Stranger Things",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Stranger Things",
    overview:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    popularity: 4070.154,
    poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    first_air_date: "2016-07-15",
    vote_average: 8.627,
    vote_count: 11919,
  },
  {
    adult: false,
    backdrop_path: "/6d1mHKcozT5AaZeI76ehJrBt0hr.jpg",
    genre_ids: [27],
    id: 864370,
    media_type: "movie",
    title: "Incantation",
    original_language: "zh",
    original_title: "咒",
    overview:
      "Inspired by a true story of a family who believed they were possessed by spirits, this film follows a woman who must protect her child from a curse.\r WARNING: This is a cursed video, it might contain certain risks to watch ; For those who dares to follow, please solve the puzzle of my daughter's curse with me .",
    popularity: 57.393,
    poster_path: "/6zltP23zLGPogsHZUazSrrwNuKs.jpg",
    release_date: "2022-03-18",
    video: false,
    vote_average: 7.476,
    vote_count: 21,
  },
  {
    adult: false,
    backdrop_path: "/zEmbjSuX9TSDC7Au5dGmO2wucZw.jpg",
    genre_ids: [18, 80],
    id: 155537,
    media_type: "tv",
    name: "Black Bird",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Black Bird",
    overview:
      "As Jimmy Keene begins a 10-year prison sentence, he gets an incredible offer: If he can elicit a confession from suspected killer Larry Hall, Jimmy will be freed. Completing this mission becomes the challenge of a lifetime.",
    popularity: 138.355,
    poster_path: "/bLhy0BRGk9IDZ4h6pRMkjjgcaE9.jpg",
    first_air_date: "2022-07-07",
    vote_average: 7.8,
    vote_count: 12,
  },
  {
    adult: false,
    backdrop_path: "/voeQ3GolYnXSs9HH0MbMHazNiWm.jpg",
    genre_ids: [80],
    id: 201331,
    media_type: "tv",
    name: "The Longest Night",
    origin_country: ["ES"],
    original_language: "es",
    original_name: "La noche más larga",
    overview:
      "Armed forces surround a psychiatric prison in order to abduct an incarcerated serial killer — but aren't prepared for the battle that ensues.",
    popularity: 109.56,
    poster_path: "/8tLBotLw2BKXEOgI5Wpsy7VXkND.jpg",
    first_air_date: "2022-07-08",
    vote_average: 6.2,
    vote_count: 8,
  },
  {
    adult: false,
    backdrop_path: "/kSQQVqXtTAkNrFoXz8KjN8XEncY.jpg",
    genre_ids: [35, 10765],
    id: 132188,
    media_type: "tv",
    name: "Boo, Bitch",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Boo, Bitch",
    overview:
      "Two senior BFFs make a last-ditch attempt to be seen. But when one of them becomes a ghost, she'll need to really live her best life — while she can.",
    popularity: 99.922,
    poster_path: "/b3zagQAHUUePg29xjp9SYoxtsv7.jpg",
    first_air_date: "2022-07-08",
    vote_average: 8.0,
    vote_count: 9,
  },
  {
    adult: false,
    backdrop_path: "/3XAPsH5yS6p54P5PkAtxJfnvlhU.jpg",
    genre_ids: [18, 10749],
    id: 968739,
    media_type: "movie",
    title: "Dangerous Liaisons",
    original_language: "fr",
    original_title: "Les liaisons dangereuses",
    overview:
      "The innocent Célène might be falling in love with popular surfer Tristan at her new school. But she has no idea that, in actuality, she’s the object of a cruel bet between Tristan and Instagram influencer Vanessa.",
    popularity: 74.323,
    poster_path: "/opTwqTgREzvP67ERVrqt0ApXbeV.jpg",
    release_date: "2022-07-08",
    video: false,
    vote_average: 5.8,
    vote_count: 34,
  },
  {
    adult: false,
    backdrop_path: "/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg",
    genre_ids: [28, 18],
    id: 361743,
    media_type: "movie",
    title: "Top Gun: Maverick",
    original_language: "en",
    original_title: "Top Gun: Maverick",
    overview:
      "After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.",
    popularity: 1158.185,
    poster_path: "/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    release_date: "2022-05-24",
    video: false,
    vote_average: 8.359,
    vote_count: 1511,
  },
  {
    adult: false,
    backdrop_path: "/yQTQL9pliY6vpRt8HkjUJrKymBb.jpg",
    genre_ids: [10759, 18],
    id: 120911,
    media_type: "tv",
    name: "The Terminal List",
    origin_country: ["US"],
    original_language: "en",
    original_name: "The Terminal List",
    overview:
      "Navy SEAL Commander James Reece turns to vengeance as he investigates the mysterious forces behind the murder of his entire platoon. Free from the military’s command structure, Reece applies the lessons he’s learned from nearly two decades of warfare to hunt down the people responsible.",
    popularity: 1753.263,
    poster_path: "/71f3JHlJCP6V7LhHHiKZgjtFxZw.jpg",
    first_air_date: "2022-06-30",
    vote_average: 8.724,
    vote_count: 136,
  },
  {
    adult: false,
    backdrop_path: "/qKVOTKPPtvoXd75L1HOSBPLtKWS.jpg",
    genre_ids: [16, 28, 14, 878],
    id: 761898,
    media_type: "movie",
    title: "Sword Art Online the Movie -Progressive- Aria of a Starless Night",
    original_language: "ja",
    original_title:
      "劇場版 ソードアート・オンライン プログレッシブ 星なき夜のアリア",
    overview:
      "One month after Kayaba Akihiko's game of death began, the death toll continues to rise, two thousand players having already lost their lives to the ultra-difficult VRMMO world of Sword Art Online. On the day of the strategy meeting to plan out the first-floor boss battle, Kirito, a solo player who vows to fight alone to get stronger, runs into a rare, high-level female player. She gracefully dispatches powerful monsters with a single rapier that flashes like a shooting star in the night...",
    popularity: 162.868,
    poster_path: "/yD9RhgIVydQNBK7OLEbCWYcWMUd.jpg",
    release_date: "2021-10-30",
    video: false,
    vote_average: 8.0,
    vote_count: 19,
  },
  {
    adult: false,
    backdrop_path: "/ocUp7DJBIc8VJgLEw1prcyK1dYv.jpg",
    genre_ids: [28, 12, 878],
    id: 634649,
    media_type: "movie",
    title: "Spider-Man: No Way Home",
    original_language: "en",
    original_title: "Spider-Man: No Way Home",
    overview:
      "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    popularity: 2172.096,
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    release_date: "2021-12-15",
    video: false,
    vote_average: 8.061,
    vote_count: 14030,
  },
  {
    adult: false,
    backdrop_path: "/wp3vpSWAIjKSEeYb8F5NSZfONqw.jpg",
    genre_ids: [28, 12, 878],
    id: 545611,
    media_type: "movie",
    title: "Everything Everywhere All at Once",
    original_language: "en",
    original_title: "Everything Everywhere All at Once",
    overview:
      "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.",
    popularity: 385.136,
    poster_path: "/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    release_date: "2022-03-24",
    video: false,
    vote_average: 8.298,
    vote_count: 914,
  },
  {
    adult: false,
    backdrop_path: "/8vn4eis4xk6cnOnAuAcyzPbqVb0.jpg",
    genre_ids: [10749, 18],
    id: 745376,
    media_type: "movie",
    title: "Hello, Goodbye, and Everything in Between",
    original_language: "en",
    original_title: "Hello, Goodbye, and Everything in Between",
    overview:
      "Clare and Aidan, who after making a pact that they would break up before college, find themselves retracing the steps of their relationship on their last evening as a couple. The epic date leads them to familiar landmarks, unexpected places, and causes them to question whether high school love is meant to last.",
    popularity: 234.749,
    poster_path: "/n05spbekRTfx0OG4FI7bFssYlfo.jpg",
    release_date: "2022-07-06",
    video: false,
    vote_average: 5.9,
    vote_count: 33,
  },
  {
    adult: false,
    backdrop_path: "/5PnypKiSj2efSPqThNjTXz8jwOg.jpg",
    genre_ids: [14, 28],
    id: 759175,
    media_type: "movie",
    title: "The Princess",
    original_language: "en",
    original_title: "The Princess",
    overview:
      "A beautiful, strong-willed young royal refuses to wed the cruel sociopath to whom she is betrothed and is kidnapped and locked in a remote tower of her father’s castle. With her scorned, vindictive suitor intent on taking her father’s throne, the princess must protect her family and save the kingdom.",
    popularity: 553.631,
    poster_path: "/gt9s8TtZZ36TXF1CE1y19rSpOZu.jpg",
    release_date: "2022-06-16",
    video: false,
    vote_average: 6.425,
    vote_count: 87,
  },
  {
    adult: false,
    backdrop_path: "/rlCRM7U5g2hcU1O8ylGcqsMYHIP.jpg",
    genre_ids: [10765, 10759, 35],
    id: 92782,
    media_type: "tv",
    name: "Ms. Marvel",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Ms. Marvel",
    overview:
      "A great student, avid gamer, and voracious fan-fic scribe, Kamala Khan has a special affinity for superheroes, particularly Captain Marvel. However, she struggles to fit in at home and at school — that is, until she gets superpowers like the heroes she’s always looked up to. Life is easier with superpowers, right?",
    popularity: 1545.702,
    poster_path: "/cdkyMYdu8ao26XOBvilNzLneUg1.jpg",
    first_air_date: "2022-06-08",
    vote_average: 7.5,
    vote_count: 266,
  },
];
export default function (req, res) {
  if (req.method === "GET") {
    res.status(200).json(movies);
  }
}
